### ISSUE TITLE
Enable Meteor hot reloading

### ISSUE THREAD

**Issue by mquandalle** [sandstorm-io/meteor-spk#14]
Hot reloading would make the iteration process during development much faster and enjoyable.

**Comment by kentonv** [comment]
Indeed! But running Meteor in dev mode inside the sandbox probably won't work for a number of reasons. For example, Meteor will want to download dependency packages as you add them.

We have an alternative idea: We can have a new kind of dev mode that actually runs outside the sandbox. The `spk dev` process would start the app directly and then pass its `UiView` Cap'n Proto capability off to the locally-running Sandstorm server. Sandstorm would then expose a special grain within the shell which actually directs to this external UiView rather than starting up a grain.

With this setup, it would be easy to have Meteor (or other stacks) running in dev mode. You might even not need to run inside a Linux VM -- perhaps we could make all the parts run on OSX.

Of course, you wouldn't get a perfect Sandstorm environment, in that the network would be wide open. _However_, you _would_ get the whole Sandstorm API, so it's much better than running Meteor completely independent of Sandstorm.

For now this is still all vaporware, though.
