### ISSUE TITLE
Unclear if I should use this or vagrant-spk

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/meteor-spk#18]
So now I am unclear how to port my Meteor app to Sandstorm. Should I follow instructions in README of this package, or should I follow [this doc](https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial-meteor/)?

**Comment by ocdtrekkie** [comment]
If you are trying to port your app to Sandstorm, and you use OS X, I would use vagrant-spk, as it should implement meteor-spk inside the VM it creates. If you're on Linux, using meteor-spk directly is faster.

I personally prefer to use the native spk tool on a Linux box, but the Sandstorm.io devs suggest new users all use vagrant-spk pretty much, because it's a common environment that they're focused on the user experience of.

**Comment by mitar** [comment]
> If you are trying to port your app to Sandstorm, and you use OS X, I would use vagrant-spk

I do.

**Comment by mitar** [comment]
Hm, reading more about this, I think this package should definitely mention in the README that there are two ways to go about this.

**Comment by kentonv** [comment]
I've updated the readme. Thanks for the reminder.
