### ISSUE TITLE
New meteor-spk release for Meteor 1.6.1 for Wekan?

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/meteor-spk#30]
Hi,
Wekan now works with Meteor 1.6.1:
https://github.com/peerlibrary/meteor-computed-field/issues/13#issuecomment-368352580

Can you make new meteor-spk release for Meteor 1.6.1 ?

BR,
xet7

**Comment by xet7** [comment]
@kentonv 

^

**Comment by ocdtrekkie** [comment]
Rocket.Chat is on Meter 1.6.1.1, and would probably push releases again if we can get vagrant-spk's Meteor building capability back in order. It depends on meteor-spk, so to do that, I need this.

See https://github.com/RocketChat/Rocket.Chat/pull/9663

**Comment by kentonv** [comment]
Did you actually try to build a package and have it fail somehow, or are you just assuming meteor-spk needs an update? I believe meteor-spk should only need an update when Meteor switches major releases of Node.js. It doesn't normally need updating for every single Meteor release.

That said, I've pushed a new release based on Meteor 1.6.1.1.

**Comment by ocdtrekkie** [comment]
Can't speak for xet7, though he usually tests things.

I haven't tried to tackle vagrant-spk's Meteor stack yet, but it explicitly codes meteor-spk versions and Meteor versions, and hence I suspect a high likelihood of it exploding violently when I try to update it, since it hasn't worked since Meteor 1.4, I think. At the very least, in my case, it will probably simplify troubleshooting to be working on a current release built on a current version.
